export const backendURL = "http://localhost:8080/"
export const imageUploadURL = backendURL + "image/"
export const imageServeURL = backendURL + "uploaded/"
export const productBackendURL = backendURL + "product"
export const userBackendURL = backendURL + "user"
export const oauthTokenBackendURL = backendURL + "oauth/token"
